# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-21 06:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortcourse',
            name='fee',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='fee',
            field=models.CharField(max_length=250),
        ),
    ]
